// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANnuaDSi5aymmIVRxaybPlzxH-jPZL7Kw',
    appId: '1:105251594410:web:2146b8018cd5183e5af0d3',
    messagingSenderId: '105251594410',
    projectId: 'eshop-vibeswine',
    authDomain: 'eshop-vibeswine.firebaseapp.com',
    storageBucket: 'eshop-vibeswine.appspot.com',
    measurementId: 'G-5R9Z3SZKDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy1LUzEkSNUmo0dRFkh53FOGtlxC0t2KQ',
    appId: '1:105251594410:android:7d66718e9d68d01e5af0d3',
    messagingSenderId: '105251594410',
    projectId: 'eshop-vibeswine',
    storageBucket: 'eshop-vibeswine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVrUQ7u_tXBcOfl5O91ES8ClBkhpL1CB4',
    appId: '1:105251594410:ios:be0de471e7ce9f555af0d3',
    messagingSenderId: '105251594410',
    projectId: 'eshop-vibeswine',
    storageBucket: 'eshop-vibeswine.appspot.com',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVrUQ7u_tXBcOfl5O91ES8ClBkhpL1CB4',
    appId: '1:105251594410:ios:be0de471e7ce9f555af0d3',
    messagingSenderId: '105251594410',
    projectId: 'eshop-vibeswine',
    storageBucket: 'eshop-vibeswine.appspot.com',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANnuaDSi5aymmIVRxaybPlzxH-jPZL7Kw',
    appId: '1:105251594410:web:98960252d6aaa16b5af0d3',
    messagingSenderId: '105251594410',
    projectId: 'eshop-vibeswine',
    authDomain: 'eshop-vibeswine.firebaseapp.com',
    storageBucket: 'eshop-vibeswine.appspot.com',
    measurementId: 'G-H9Z0Z1FE20',
  );
}
